
global msg_laser msg_sonar0 msg_sonar1 msg_sonar2 msg_sonar3 msg_sonar4 msg_sonar5 msg_sonar6 msg_sonar7

plot(msg_laser);
display(sprintf('\tSONARS: %f; %f; %f; %f; %f; %f; %f; %f;',...
        msg_sonar0.Range_, msg_sonar1.Range_, msg_sonar2.Range_,...
        msg_sonar3.Range_, msg_sonar4.Range_, msg_sonar5.Range_,...
        msg_sonar6.Range_, msg_sonar7.Range_));